### ISSUE TITLE
Screen goes blank after connecting to a system

### ISSUE THREAD

**Issue by Ryrye09** [SomeGuru/GetIntelCloud#3]
Screen goes blank after connecting to a system. When I refresh it connects for 5 to 10 seconds after which it goes blank. Tried this on 20 systems. Four of the other teammates are also having the same issue. Please let us know if there is any additional information needed.

**Comment by SomeGuru** [comment]
Hi @Ryrye09 ,

Can you give clarity to this bug report? It looks like some information to reproduce this failure is missing... I am assuming this is when you are in the display and someone else logs on and then your screen goes blank is that correct or am I wrong?

Thanks,
SomeGuru

**Comment by Ryrye09** [comment]
Step 1: change the view to tile mode
Step 2: Connect to a system in a particular group
Step 3: One it connects right click and select desktop
Step 4: Once the desktop opens screen goes blank in a couple of seconds

**Comment by SomeGuru** [comment]
Hi @Ryrye09,

This has been reproduced and esclated to the development for review. Please allow a few days and then we will follow up and test again.

Thank you,
SomeGuru
