### ISSUE TITLE
Mesh Central Router not connecting properly

### ISSUE THREAD

**Issue by Ryrye09** [SomeGuru/GetIntelCloud#4]
When using the mesh central router to remotely connect to a system using one of the following HTTPS,HTTP, RDP, and MAPPING will give out errors and unable to connect to the system.

When you log into the router find the system you want to remote into and click on https or http it will open a tab in the web browser , 5 to 10 seconds of loading the browser will display cannot find local host. 

When selecting rdp, a window comes up called remote desktop connection click connect, another window comes up click connect, in the process of establishing connection to the system and error message comes up "because of a protocol error detected at the client **(code 0x1104)**, this session will be disconnected". 

The mapping option, after setting up your mapping configuration. It will go through the same set of steps as the rpd and when trying to establish connect to the system it will give the same error as the rpd "because of a protocol error detected at the client **(code 0x1104)**, this session will be disconnected".

**Comment by SomeGuru** [comment]
Resolved in 5.50+ upgrade happening this week. Please test and reopen if needed.
