### ISSUE TITLE
My Devices not displayed using List mode on Firefox

### ISSUE THREAD

**Issue by MrBadger42** [SomeGuru/GetIntelCloud#5]
Initially was able to see the devices I had added in "My Devices" using the "List" view. However, after deleting a group on another session, I could no longer see my devices using "List". If I switched to "Desktops" or "Columns" they appeared. I tried logging out the offending session and logging back in but it didn't seem to change the situation. I do NOT see this on Chrome or on the web browser on the RaspberryPi device being used for this experiment.

**Comment by SomeGuru** [comment]
Issue is being looked into right now. Will get back to you once more is identified or we need additional information. Thank you.

**Comment by SomeGuru** [comment]
Please give more details on steps to reproduce this issue, and is this still and issue you are seeing, please include screen grabs if you are able to, also details of the OS being used to replicate this issue would be helpful.

Thank you,
SomeGuru

**Comment by SomeGuru** [comment]
No response, going to close this issue as resolved.
